plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/yaroslavponomarov/Documents/Programming/polina-pavlova-coach"
publishOrigin = "default"
command = "npm run build"
commandOrigin = "heuristics"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]